name: Deploy Database Schema

on:
  workflow_dispatch:

jobs:
  deploy-schema:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Set project from Secret Manager
      run: |
        gcloud config set project $(gcloud secrets versions access latest --secret="GCP_PROJECT_ID")

    - name: Remove old schema file from VM
      run: |
        gcloud compute ssh $(gcloud secrets versions access latest --secret="VM_INSTANCE_NAME") --zone=$(gcloud secrets versions access latest --secret="VM_ZONE") --command="cd ~ && rm -f create_schema.sql"

    - name: Upload schema file to VM
      run: |
        gcloud compute scp create_schema.sql $(gcloud secrets versions access latest --secret="VM_INSTANCE_NAME"):~/ --zone=$(gcloud secrets versions access latest --secret="VM_ZONE")

    - name: Check and start database service
      run: |
        echo "Checking database service status..."
        gcloud compute ssh $(gcloud secrets versions access latest --secret="VM_INSTANCE_NAME") --zone=$(gcloud secrets versions access latest --secret="VM_ZONE") --command="sudo systemctl status postgresql || sudo systemctl start postgresql"
        sleep 5

    - name: Apply schema changes
      run: |
        echo "Applying schema changes from create_schema.sql..."
        gcloud compute ssh $(gcloud secrets versions access latest --secret="VM_INSTANCE_NAME") \
          --zone=$(gcloud secrets versions access latest --secret="VM_ZONE") \
          --command='
            cd ~ &&
            PGPASSWORD=$(gcloud secrets versions access latest --secret=CLOUDSQL_PASSWORD) \
            psql -h localhost -U postgres -d prompt-evaluator-db -f create_schema.sql
          '

    - name: Verify schema deployment
      run: |
        echo "Verifying schema deployment..."
        gcloud compute ssh $(gcloud secrets versions access latest --secret="VM_INSTANCE_NAME") --zone=$(gcloud secrets versions access latest --secret="VM_ZONE") --command="cd ~ && PGPASSWORD=\$(gcloud secrets versions access latest --secret='CLOUDSQL_PASSWORD') psql -h localhost -U postgres -d prompt-evaluator-db -c '\dt'"

    - name: Restart application containers
      run: |
        echo "Restarting application containers to ensure they pick up schema changes..."
        gcloud compute ssh $(gcloud secrets versions access latest --secret="VM_INSTANCE_NAME") --zone=$(gcloud secrets versions access latest --secret="VM_ZONE") --command="cd ~/promptevaluator && docker-compose restart"

    - name: Schema deployment status
      run: |
        echo "✅ Database schema deployment completed!"
        echo "📊 Database: $(gcloud secrets versions access latest --secret="VM_INSTANCE_NAME")"
        echo "📝 Commit: ${{ github.sha }}"
        echo "🕒 Timestamp: $(date)"
        echo "✅ Schema changes applied successfully"